# Generated by Django 2.1.1 on 2018-09-22 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180920_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 5, 30, 27, 965827, tzinfo=utc)),
        ),
    ]
