# Generated by Django 2.1.1 on 2018-09-30 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180922_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 30, 7, 53, 22, 197745, tzinfo=utc)),
        ),
    ]
